# Generated by Django 5.1.6 on 2025-03-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('hmotnost', models.IntegerField(blank=True, null=True)),
                ('obvod', models.IntegerField(blank=True, null=True)),
                ('ucel', models.CharField(max_length=70)),
                ('znacka', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Znacka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znacka', models.CharField(max_length=300)),
            ],
        ),
    ]
