# Generated by Django 5.1.6 on 2025-03-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Znacka',
        ),
        migrations.RenameField(
            model_name='ball',
            old_name='znacka',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='ball',
            old_name='obvod',
            new_name='diameter',
        ),
        migrations.RenameField(
            model_name='ball',
            old_name='ucel',
            new_name='purpose',
        ),
        migrations.RenameField(
            model_name='ball',
            old_name='hmotnost',
            new_name='weght',
        ),
    ]
