# Generated by Django 5.1.7 on 2025-03-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customer_lifetime_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lifetime_purchases',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
