# Generated by Django 5.1.6 on 2025-03-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brand_delete_znacka_rename_znacka_ball_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ball',
            old_name='weght',
            new_name='weight',
        ),
    ]
