# Generated by Django 5.1.7 on 2025-03-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customer_lifetime_purchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='lifetime_purchases',
        ),
    ]
