# Generated by Django 5.2 on 2025-04-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_ball_price_alter_customer_customer_email_and_more'),
        ('main', '0006_alter_purchase_total_price'),
    ]

    operations = [
    ]
