# Generated by Django 5.1.7 on 2025-05-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20250425_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
